$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
  $("#confirm").click(function(){
    $("#namealert").hide();
    $("#adresalert").hide();
    var naam = $("#name").val();
    var adres = $("#adres").val();
    if(!/^\D*$/.test(naam)){
      $("#namealert").fadeIn("slow");
    }
    if(!/^[a-zA-Z$]*\s[1-9]*$/.test(adres)){
      $("#adresalert").fadeIn("slow");
    }else{
      $("#formsent").show();
    }
  });
  $("#name").hover(function(){
    $("#naaminfo").collapse("show");
  },
  function(){
    $("#naaminfo").collapse("hide");
  });
  $("#adres").hover(function(){
    $("#adresinfo").collapse("show");
  },
  function(){
    $("#adresinfo").collapse("hide");
  });
});
